services:
  # MongoDB Database Service
  mongodb:
    image: mongo:7-jammy
    container_name: rbac-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-rbac_db}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - rbac-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: rbac-app
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-5000}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/${MONGO_DB_NAME:-rbac_db}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_change_in_production}
      JWT_EXPIRE: ${JWT_EXPIRE:-7d}
      CORS_URL: ${CORS_URL:-http://localhost:3000}
    ports:
      - "${APP_PORT:-5000}:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - rbac-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:5000/api/auth/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); });",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development Service (for local development with hot reload)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: rbac-app-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: ${PORT:-5000}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/${MONGO_DB_NAME:-rbac_db}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_change_in_production}
      JWT_EXPIRE: ${JWT_EXPIRE:-7d}
      CORS_URL: ${CORS_URL:-http://localhost:3000}
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - rbac-network
    profiles:
      - dev

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  rbac-network:
    driver: bridge
